### ISSUE TITLE
Добавить имя игрока при смене подачи

### ISSUE THREAD

**Issue by howtobeahuman** [karachev/scoreboard#1]
В диалоговом окне "Смена подающего" было бы здорово показывать имя того, кто теперь подаёт: «Смена подающего. Подаёт Игрок1.»

**Comment by karachev** [comment]
it is unreal

**Comment by howtobeahuman** [comment]
I'm sorry I don't understand you. try again later

**Comment by karachev** [comment]
Добавил функционал
